# Default values for lambda-link.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

image:
  repository: public.ecr.aws/g4k0u1s2/node-latency-for-k8s
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: v0.1.10
  digest: sha256:a66ec2166d1a82f09ca2f322896b97867bca5ec47f06f1fe4f819684c0b46b9f

nameOverride: ""
fullnameOverride: ""

# The value of the label is statically defined as a constant named oneShotExcludeLabel in the main.go
nodeLabelKey: "node-latency-for-k8s-exclude-pod"

# If the OTeL collector is running as a daemonset we'll pull in the node ip for the OTEL_EXPORTER_OTLP_ENDPOINT env variable, otherwise
# set OTEL_EXPORTER_OTLP_ENDPOINT in the env values array below
oTeLCollectorDaemonset: true

serviceAccount:
  # Specifies whether a service account should be created
  create: true
  # Annotations to add to the service account
  annotations: {}
  # The name of the service account to use.
  # If not set and create is true, a name is generated using the fullname template
  name: "node-latency-for-k8s"

podMonitor:
  create: false

podAnnotations: {}

podSecurityContext:
  fsGroup: 0
  runAsUser: 0
  runAsGroup: 0

securityContext:
  capabilities: {}

resources:
  requests:
    cpu: 200m
    memory: 256Mi
  limits:
    memory: 256Mi

nodeSelector:
  kubernetes.io/arch: amd64
  kubernetes.io/os: linux
tolerations: []
affinity: {}
priorityClassName: ""

env:
  - name: PROMETHEUS_METRICS
    value: "true"
  - name: CLOUDWATCH_METRICS
    value: "false"
  - name: OTEL_METRICS
    value: "false"
  - name: OUTPUT
    value: "markdown"
  - name: NO_COMMENTS
    value: "false"
  - name: "TIMEOUT"
    value: "300"
  - name: POD_NAMESPACE
    value: "default"
  - name: NODE_NAME
    valueFrom:
      fieldRef:
        fieldPath: spec.nodeName
