apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: node-latency-for-k8s
  labels:
    {{- include "node-latency-for-k8s.labels" . | nindent 4 }}
rules:
- apiGroups:
  - ""
  resources:
  - pods
  verbs:
  - list
- apiGroups:
  - ""
  resources:
  - nodes
  verbs:
  - patch
