AWSTemplateFormatVersion: "2010-09-09"
Description: Resources used by K8s Node Latency
Parameters:
  ClusterName:
    Type: String
    Description: "EKS cluster name"
Resources:
  K8sNodeLatencyPolicy:
    Type: AWS::IAM::ManagedPolicy
    Properties:
      ManagedPolicyName: !Sub "${ClusterName}-node-latency-for-k8s-policy"
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Action:
              - cloudwatch:PutMetricData
              - ec2:DescribeTags
              - ec2:DescribeFleets
              - ec2:DescribeInstances
            Resource: "*"
