name: release
on:
  push:
    tags:
      - "v*.*.*"
  workflow_dispatch:
permissions:
  id-token: write
  pull-requests: write
  contents: write
jobs:
  release:
    runs-on: ubuntu-latest
    if: github.repository == 'awslabs/node-latency-for-k8s'
    steps:
      -
        name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - run: sed -En 's/^go[[:space:]]+([[:digit:].]+)$/GO_VERSION=\1/p' go.mod >> $GITHUB_ENV
        shell: bash
      - uses: actions/setup-go@v3
        with:
          go-version: ${{ env.GO_VERSION }}
          check-latest: true
      - uses: actions/cache@v3
        with:
          path: |
            ~/.cache/go-build
            ~/go/pkg/
            ~/go/bin/
          key: ${{ runner.os }}-go-cache-${{ hashFiles('go.sum', 'hack/toolchain.sh') }}
      - run: make toolchain
      - uses: aws-actions/configure-aws-credentials@v1-node16
        with:
          role-to-assume: arn:aws:iam::750221471634:role/Github
          aws-region: us-east-1
      - env:
          NLK_KO_DOCKER_REPO: public.ecr.aws/m0e9w1v1
        run: |
          make publish
      -
        name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v4
        with:
          distribution: goreleaser
          version: latest
          args: release --skip-validate
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      -
        name: Upload assets
        uses: actions/upload-artifact@v3
        with:
          name: node-latency-for-k8s
          path: dist/*
      - run: |
          echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV
          git config user.name "Release"
          git config user.email "release@users.noreply.github.com"
          git remote set-url origin https://x-access-token:${GITHUB_TOKEN}@github.com/${GITHUB_REPO}
          git config pull.rebase false

          BRANCH_NAME="release-${RELEASE_VERSION}"
          git checkout -b "${BRANCH_NAME}"
          git add charts/
          git commit -m "Release updates ${RELEASE_VERSION}."
          git push --set-upstream origin "${BRANCH_NAME}"
          gh pr create --title "chore: Release ${RELEASE_VERSION}" --body "Release ${RELEASE_VERSION}" --base main --head "release-${RELEASE_VERSION}"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_REPO: ${{ github.repository }}
